// 100 niveaux du Jardin du Bambou : nom poetique + difficulte (nombre de coups de melange)
// Progression de 10 a 200 coups sur les 100 premiers niveaux, puis plateau autour de 200
// pour les jardins de l'Eau et des Braises (contemplatifs plutot que laborieux).
window.NS_LEVELS_DATA = [
    { level: 1, name: "Premier Bambou", shuffleMoves: 10 },
    { level: 2, name: "Premier Sentier", shuffleMoves: 12 },
    { level: 3, name: "Premier Souffle", shuffleMoves: 14 },
    { level: 4, name: "Premier Reflet", shuffleMoves: 16 },
    { level: 5, name: "Premier Murmure", shuffleMoves: 18 },
    { level: 6, name: "Première Pierre", shuffleMoves: 20 },
    { level: 7, name: "Première Mousse", shuffleMoves: 22 },
    { level: 8, name: "Première Brise", shuffleMoves: 23 },
    { level: 9, name: "Première Rosée", shuffleMoves: 25 },
    { level: 10, name: "Première Lumière", shuffleMoves: 27 },
    { level: 11, name: "Doux Bambou", shuffleMoves: 29 },
    { level: 12, name: "Doux Sentier", shuffleMoves: 31 },
    { level: 13, name: "Doux Souffle", shuffleMoves: 33 },
    { level: 14, name: "Doux Reflet", shuffleMoves: 35 },
    { level: 15, name: "Doux Murmure", shuffleMoves: 37 },
    { level: 16, name: "Douce Pierre", shuffleMoves: 39 },
    { level: 17, name: "Douce Mousse", shuffleMoves: 41 },
    { level: 18, name: "Douce Brise", shuffleMoves: 43 },
    { level: 19, name: "Douce Rosée", shuffleMoves: 45 },
    { level: 20, name: "Douce Lumière", shuffleMoves: 46 },
    { level: 21, name: "Léger Bambou", shuffleMoves: 48 },
    { level: 22, name: "Léger Sentier", shuffleMoves: 50 },
    { level: 23, name: "Léger Souffle", shuffleMoves: 52 },
    { level: 24, name: "Léger Reflet", shuffleMoves: 54 },
    { level: 25, name: "Léger Murmure", shuffleMoves: 56 },
    { level: 26, name: "Légère Pierre", shuffleMoves: 58 },
    { level: 27, name: "Légère Mousse", shuffleMoves: 60 },
    { level: 28, name: "Légère Brise", shuffleMoves: 62 },
    { level: 29, name: "Légère Rosée", shuffleMoves: 64 },
    { level: 30, name: "Légère Lumière", shuffleMoves: 66 },
    { level: 31, name: "Paisible Bambou", shuffleMoves: 68 },
    { level: 32, name: "Paisible Sentier", shuffleMoves: 69 },
    { level: 33, name: "Paisible Souffle", shuffleMoves: 71 },
    { level: 34, name: "Paisible Reflet", shuffleMoves: 73 },
    { level: 35, name: "Paisible Murmure", shuffleMoves: 75 },
    { level: 36, name: "Paisible Pierre", shuffleMoves: 77 },
    { level: 37, name: "Paisible Mousse", shuffleMoves: 79 },
    { level: 38, name: "Paisible Brise", shuffleMoves: 81 },
    { level: 39, name: "Paisible Rosée", shuffleMoves: 83 },
    { level: 40, name: "Paisible Lumière", shuffleMoves: 85 },
    { level: 41, name: "Silencieux Bambou", shuffleMoves: 87 },
    { level: 42, name: "Silencieux Sentier", shuffleMoves: 89 },
    { level: 43, name: "Silencieux Souffle", shuffleMoves: 91 },
    { level: 44, name: "Silencieux Reflet", shuffleMoves: 93 },
    { level: 45, name: "Silencieux Murmure", shuffleMoves: 94 },
    { level: 46, name: "Silencieuse Pierre", shuffleMoves: 96 },
    { level: 47, name: "Silencieuse Mousse", shuffleMoves: 98 },
    { level: 48, name: "Silencieuse Brise", shuffleMoves: 100 },
    { level: 49, name: "Silencieuse Rosée", shuffleMoves: 102 },
    { level: 50, name: "Silencieuse Lumière", shuffleMoves: 104 },
    { level: 51, name: "Discret Bambou", shuffleMoves: 106 },
    { level: 52, name: "Discret Sentier", shuffleMoves: 108 },
    { level: 53, name: "Discret Souffle", shuffleMoves: 110 },
    { level: 54, name: "Discret Reflet", shuffleMoves: 112 },
    { level: 55, name: "Discret Murmure", shuffleMoves: 114 },
    { level: 56, name: "Discrète Pierre", shuffleMoves: 116 },
    { level: 57, name: "Discrète Mousse", shuffleMoves: 117 },
    { level: 58, name: "Discrète Brise", shuffleMoves: 119 },
    { level: 59, name: "Discrète Rosée", shuffleMoves: 121 },
    { level: 60, name: "Discrète Lumière", shuffleMoves: 123 },
    { level: 61, name: "Profond Bambou", shuffleMoves: 125 },
    { level: 62, name: "Profond Sentier", shuffleMoves: 127 },
    { level: 63, name: "Profond Souffle", shuffleMoves: 129 },
    { level: 64, name: "Profond Reflet", shuffleMoves: 131 },
    { level: 65, name: "Profond Murmure", shuffleMoves: 133 },
    { level: 66, name: "Profonde Pierre", shuffleMoves: 135 },
    { level: 67, name: "Profonde Mousse", shuffleMoves: 137 },
    { level: 68, name: "Profonde Brise", shuffleMoves: 139 },
    { level: 69, name: "Profonde Rosée", shuffleMoves: 141 },
    { level: 70, name: "Profonde Lumière", shuffleMoves: 142 },
    { level: 71, name: "Serein Bambou", shuffleMoves: 144 },
    { level: 72, name: "Serein Sentier", shuffleMoves: 146 },
    { level: 73, name: "Serein Souffle", shuffleMoves: 148 },
    { level: 74, name: "Serein Reflet", shuffleMoves: 150 },
    { level: 75, name: "Serein Murmure", shuffleMoves: 152 },
    { level: 76, name: "Sereine Pierre", shuffleMoves: 154 },
    { level: 77, name: "Sereine Mousse", shuffleMoves: 156 },
    { level: 78, name: "Sereine Brise", shuffleMoves: 158 },
    { level: 79, name: "Sereine Rosée", shuffleMoves: 160 },
    { level: 80, name: "Sereine Lumière", shuffleMoves: 162 },
    { level: 81, name: "Ancien Bambou", shuffleMoves: 164 },
    { level: 82, name: "Ancien Sentier", shuffleMoves: 165 },
    { level: 83, name: "Ancien Souffle", shuffleMoves: 167 },
    { level: 84, name: "Ancien Reflet", shuffleMoves: 169 },
    { level: 85, name: "Ancien Murmure", shuffleMoves: 171 },
    { level: 86, name: "Ancienne Pierre", shuffleMoves: 173 },
    { level: 87, name: "Ancienne Mousse", shuffleMoves: 175 },
    { level: 88, name: "Ancienne Brise", shuffleMoves: 177 },
    { level: 89, name: "Ancienne Rosée", shuffleMoves: 179 },
    { level: 90, name: "Ancienne Lumière", shuffleMoves: 181 },
    { level: 91, name: "Sacré Bambou", shuffleMoves: 183 },
    { level: 92, name: "Sacré Sentier", shuffleMoves: 185 },
    { level: 93, name: "Sacré Souffle", shuffleMoves: 187 },
    { level: 94, name: "Sacré Reflet", shuffleMoves: 188 },
    { level: 95, name: "Sacré Murmure", shuffleMoves: 190 },
    { level: 96, name: "Sacrée Pierre", shuffleMoves: 192 },
    { level: 97, name: "Sacrée Mousse", shuffleMoves: 194 },
    { level: 98, name: "Sacrée Brise", shuffleMoves: 196 },
    { level: 99, name: "Sacrée Rosée", shuffleMoves: 198 },
    { level: 100, name: "Sacrée Lumière", shuffleMoves: 200 },
    { level: 101, name: "Limpide Courant", shuffleMoves: 202 },
    { level: 102, name: "Limpide Ressac", shuffleMoves: 198 },
    { level: 103, name: "Limpide Ruisseau", shuffleMoves: 204 },
    { level: 104, name: "Limpide Miroir", shuffleMoves: 194 },
    { level: 105, name: "Limpide Remous", shuffleMoves: 196 },
    { level: 106, name: "Limpide Source", shuffleMoves: 196 },
    { level: 107, name: "Limpide Onde", shuffleMoves: 202 },
    { level: 108, name: "Limpide Écume", shuffleMoves: 194 },
    { level: 109, name: "Limpide Braise", shuffleMoves: 200 },
    { level: 110, name: "Limpide Flamme", shuffleMoves: 194 },
    { level: 111, name: "Insondable Courant", shuffleMoves: 196 },
    { level: 112, name: "Insondable Ressac", shuffleMoves: 204 },
    { level: 113, name: "Insondable Ruisseau", shuffleMoves: 204 },
    { level: 114, name: "Insondable Miroir", shuffleMoves: 196 },
    { level: 115, name: "Insondable Remous", shuffleMoves: 200 },
    { level: 116, name: "Insondable Source", shuffleMoves: 196 },
    { level: 117, name: "Insondable Onde", shuffleMoves: 204 },
    { level: 118, name: "Insondable Écume", shuffleMoves: 194 },
    { level: 119, name: "Insondable Braise", shuffleMoves: 196 },
    { level: 120, name: "Insondable Flamme", shuffleMoves: 200 },
    { level: 121, name: "Ardent Courant", shuffleMoves: 194 },
    { level: 122, name: "Ardent Ressac", shuffleMoves: 204 },
    { level: 123, name: "Ardent Ruisseau", shuffleMoves: 194 },
    { level: 124, name: "Ardent Miroir", shuffleMoves: 200 },
    { level: 125, name: "Ardent Remous", shuffleMoves: 194 },
    { level: 126, name: "Ardente Source", shuffleMoves: 198 },
    { level: 127, name: "Ardente Onde", shuffleMoves: 200 },
    { level: 128, name: "Ardente Écume", shuffleMoves: 204 },
    { level: 129, name: "Ardente Braise", shuffleMoves: 198 },
    { level: 130, name: "Ardente Flamme", shuffleMoves: 196 },
    { level: 131, name: "Ultime Courant", shuffleMoves: 200 },
    { level: 132, name: "Ultime Ressac", shuffleMoves: 198 },
    { level: 133, name: "Ultime Ruisseau", shuffleMoves: 196 },
    { level: 134, name: "Ultime Miroir", shuffleMoves: 200 },
    { level: 135, name: "Ultime Remous", shuffleMoves: 202 },
    { level: 136, name: "Ultime Source", shuffleMoves: 196 },
    { level: 137, name: "Ultime Onde", shuffleMoves: 196 },
    { level: 138, name: "Ultime Écume", shuffleMoves: 194 },
    { level: 139, name: "Ultime Braise", shuffleMoves: 200 },
    { level: 140, name: "Ultime Flamme", shuffleMoves: 206 },
    { level: 141, name: "Éternel Jardin", shuffleMoves: 206 },
    { level: 142, name: "Éternel Cycle", shuffleMoves: 206 },
    { level: 143, name: "Éternel Souffle", shuffleMoves: 206 },
    { level: 144, name: "Éternel Silence", shuffleMoves: 200 },
    { level: 145, name: "Éternel Chemin", shuffleMoves: 198 },
    { level: 146, name: "Éternelle Saison", shuffleMoves: 206 },
    { level: 147, name: "Éternelle Harmonie", shuffleMoves: 198 },
    { level: 148, name: "Éternelle Quiétude", shuffleMoves: 196 },
    { level: 149, name: "Éternelle Plénitude", shuffleMoves: 206 },
    { level: 150, name: "Éternelle Paix", shuffleMoves: 200 },
    { level: 151, name: "Accompli Jardin", shuffleMoves: 198 },
    { level: 152, name: "Accompli Cycle", shuffleMoves: 196 },
    { level: 153, name: "Accompli Souffle", shuffleMoves: 194 },
    { level: 154, name: "Accompli Silence", shuffleMoves: 204 },
    { level: 155, name: "Accompli Chemin", shuffleMoves: 206 },
    { level: 156, name: "Accomplie Saison", shuffleMoves: 198 },
    { level: 157, name: "Accomplie Harmonie", shuffleMoves: 194 },
    { level: 158, name: "Accomplie Quiétude", shuffleMoves: 196 },
    { level: 159, name: "Accomplie Plénitude", shuffleMoves: 194 },
    { level: 160, name: "Accomplie Paix", shuffleMoves: 194 },
];

window.NS_Levels = {
    // Renvoie les infos du niveau (nom + difficulte). Au-dela de 100, on reste sur le niveau 100
    // (fin du contenu actuel : voir Sprint 4 pour l'ajout de futurs niveaux).
    getLevelData: function(level) {
        const C = window.NS_CONSTANTS;
        const index = NS_Utils.clamp(level, 1, window.NS_LEVELS_DATA.length) - 1;
        return window.NS_LEVELS_DATA[index];
    },
    getShuffleMoves: function(level) {
        return this.getLevelData(level).shuffleMoves;
    },
    getLevelName: function(level) {
        return this.getLevelData(level).name;
    }
};